name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  server-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          npm install
          npm install sonarqube-scanner --save-dev
        working-directory: ./server
      - name: SonarQube Scan
        run: npm run sonar
        working-directory: ./server

  client-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          npm install
          npm install sonarqube-scanner --save-dev
        working-directory: ./client
      - name: SonarQube Scan
        run: npm run sonar
        working-directory: ./client
